package dev.nexus.entities;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.persistence.*;

@Entity // defines an entity for Spring
@Table(name = "items") // defines table details for Spring; name-value is the name of the table in database
@NoArgsConstructor // tells Lombok to make an empty constructor for this class
@AllArgsConstructor // tells Lombok to make a constructor for all fields of a class
@ToString // tells Lombok to modify generated bytecode & make an implementation of ToString() for the class
public class Item {
    @Id // defines the primary key for Spring
    @GeneratedValue(strategy = GenerationType.IDENTITY) // automatic primary key generation; uses IDENTITY type, which relies on IdentityCreator, which auto-increments serial primary keys.
    @Column(name = "id") // defines column details for Spring; name-value is the name of the column in database
    private int id;

    @Column(name = "item_name")
    private String name;
    @Column(name = "description")
    private String description;
    @Column(name = "status")
    private String status;
    @Column(name="supplier")
    private String supplier;
    @Column(name="potluck_id")
    private int potluckID;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public int getPotluckID() {
        return potluckID;
    }

    public void setPotluckID(int potluckID) {
        this.potluckID = potluckID;
    }

}
